// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM7XFcpCcJ8Hqu006Dvg3Gb2f0j98fHc0',
    appId: '1:976469473142:web:ae9744f6b3dc3c34dbac57',
    messagingSenderId: '976469473142',
    projectId: 'mvp-travel-prod',
    authDomain: 'mvp-travel-prod.firebaseapp.com',
    storageBucket: 'mvp-travel-prod.firebasestorage.app',
    measurementId: 'G-MKZTEXL0LB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1jBbRG66aWaLFakXKSZ-Vy5v-4JH6Zsg',
    appId: '1:976469473142:android:e5f8337952e42d82dbac57',
    messagingSenderId: '976469473142',
    projectId: 'mvp-travel-prod',
    storageBucket: 'mvp-travel-prod.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDklDTBhV40f9DnHK9QFjEKRW_UPzF-Auk',
    appId: '1:976469473142:ios:a818ab878c83188cdbac57',
    messagingSenderId: '976469473142',
    projectId: 'mvp-travel-prod',
    storageBucket: 'mvp-travel-prod.firebasestorage.app',
    iosClientId: '976469473142-cdlod1j9deamq99s8dtiit68fj0r8k73.apps.googleusercontent.com',
    iosBundleId: 'com.mvptravelandtourism.app',
  );
}
