// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANVVjoT2hWlbTrPXsXunthN7BAmUUJsxw',
    appId: '1:296884534205:web:864d0a8dd8ae709b9ab0d4',
    messagingSenderId: '296884534205',
    projectId: 'mvp-travels',
    authDomain: 'mvp-travels.firebaseapp.com',
    storageBucket: 'mvp-travels.firebasestorage.app',
    measurementId: 'G-YW2MX2HPJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAVGVgVlSujIbrgGmj5R4_6PP8BJP97Ok',
    appId: '1:296884534205:android:7744c95be4faec6c9ab0d4',
    messagingSenderId: '296884534205',
    projectId: 'mvp-travels',
    storageBucket: 'mvp-travels.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTh7ZOwaMGOXCvhhYvBwGpfalHQdk6vHE',
    appId: '1:296884534205:ios:382182a38a1996599ab0d4',
    messagingSenderId: '296884534205',
    projectId: 'mvp-travels',
    storageBucket: 'mvp-travels.firebasestorage.app',
    iosClientId: '296884534205-u12g1jphm2e7ffbdq2gg74mbcsh9qv9j.apps.googleusercontent.com',
    iosBundleId: 'com.mvptravelandtourism.app',
  );
}
